plugins {
    id 'java-library'
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.springframework.kafka:spring-kafka'
    runtimeOnly 'com.mysql:mysql-connector-j'

    implementation project(':core:core-infra')
    api project(':core:core-event')
    implementation project(':core:core-data-serializer')
}