apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':core:core-common')
    implementation project(':core:core-domain')
    implementation project(':core:core-infra')
    implementation project(':core:core-webclient')
    implementation project(':core:core-outbox-message-relay')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}
