// 유일한 실행 가능한 Spring Boot 앱
apply plugin: 'org.springframework.boot'

dependencies {
    // 모든 feature 모듈 조합
    implementation project(':core:core-common')
    implementation project(':core:core-domain')
    implementation project(':core:core-infra')
    implementation project(':modules:module-auth')
    implementation project(':modules:module-user')
    implementation project(':modules:module-voca')
    implementation project(':modules:module-writing')
    implementation project(':modules:module-reading')
    implementation project(':modules:module-conversation')
    implementation project(':modules:module-searchword')
    implementation project(':core:core-outbox-message-relay')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}
