plugins {
    id 'java-library'
}

dependencies {
    implementation project(':core:core-common')
    implementation project(':core:core-domain')

    // JPA + MySQL — api로 노출하여 하위 모듈에서 JpaRepository 사용 가능
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Redis (의존성만 추가, 구현은 추후)
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}
